/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as UploadImport } from './routes/upload'
import { Route as IndexImport } from './routes/index'
import { Route as StoriesStoryIdImport } from './routes/stories.$storyId'

// Create/Update Routes

const UploadRoute = UploadImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const StoriesStoryIdRoute = StoriesStoryIdImport.update({
  id: '/stories/$storyId',
  path: '/stories/$storyId',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/upload': {
      id: '/upload'
      path: '/upload'
      fullPath: '/upload'
      preLoaderRoute: typeof UploadImport
      parentRoute: typeof rootRoute
    }
    '/stories/$storyId': {
      id: '/stories/$storyId'
      path: '/stories/$storyId'
      fullPath: '/stories/$storyId'
      preLoaderRoute: typeof StoriesStoryIdImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/upload': typeof UploadRoute
  '/stories/$storyId': typeof StoriesStoryIdRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/upload': typeof UploadRoute
  '/stories/$storyId': typeof StoriesStoryIdRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/upload': typeof UploadRoute
  '/stories/$storyId': typeof StoriesStoryIdRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/upload' | '/stories/$storyId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/upload' | '/stories/$storyId'
  id: '__root__' | '/' | '/upload' | '/stories/$storyId'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  UploadRoute: typeof UploadRoute
  StoriesStoryIdRoute: typeof StoriesStoryIdRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  UploadRoute: UploadRoute,
  StoriesStoryIdRoute: StoriesStoryIdRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/upload",
        "/stories/$storyId"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/upload": {
      "filePath": "upload.tsx"
    },
    "/stories/$storyId": {
      "filePath": "stories.$storyId.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
